### ISSUE TITLE
can't set a Descartes pose sampler on Profile

### ISSUE THREAD

**Issue by jf---** [tesseract-robotics/tesseract_python#50]
Hi,

First, what a formidable library, so stoked having access to tesseract from python!

I'd like to contribute by porting examples from [tesseract-robotics/tesseract_planning/tree/master/tesseract_examples/src](https://github.com/tesseract-robotics/tesseract_planning/tree/master/tesseract_examples/src) to python. Also its a nice way to find my way around ;)

I'm porting a [Descartes tutorial from ROS-I training ](https://industrial-training-master.readthedocs.io/en/melodic/_source/session5/Advanced-Descartes-Path-Planning.html), 

```python

from tesseract_robotics.tesseract_motion_planners_descartes import (
    cast_DescartesPlanProfileD,
    DescartesDefaultPlanProfileD,
    sampleToolZAxis,
    PoseSamplerFn,
)


def test_zaxis_descartes():
    """

    implement the ROS-I tutotial on descartes
    basically is akin to the `puzzle_piece_example.py`, but using the `descartes` lib over `trajopt`

    https://industrial-training-master.readthedocs.io/en/melodic/_source/session5/Advanced-Descartes-Path-Planning.html

    """
    plan_profile = DescartesDefaultPlanProfileD()
    # DescartesDefaultPlanProfileD is not upcasting automatically, use helper function
    plan_profile1 = cast_DescartesPlanProfileD(plan_profile)
    pp = PoseSamplerFn(sampleToolZAxis)
    plan_profile.target_pose_sampler = pp


#     plan_profile.target_pose_sampler = pp
#     Traceback (most recent call last):
#     File "C:\Program Files (x86)\JetBrains\PyCharm 2022.3.3\plugins\python\helpers\pydev\_pydevd_bundle\pydevd_exec2.py", line 3, in Exec
#     exec(exp, global_vars, local_vars)
# File "<input>", line 1, in <module>
# File "C:\Users\jelle\miniconda3\envs\compas\lib\site-packages\tesseract_robotics\tesseract_motion_planners_descartes\tesseract_motion_planners_descartes_python.py", line 34, in set_instance_attr
# set(self, name, value)
# TypeError: in method 'DescartesDefaultPlanProfileD_target_pose_sampler_set', argument 2 of type 'tesseract_planning::PoseSamplerFn *'
# pp

```

**Comment by johnwason** [comment]
Hi @jf--- 

> First, what a formidable library, so stoked having access to tesseract from python!

I think there are over 4000 functions wrapped...

> argument 2 of type 'tesseract_planning::PoseSamplerFn *'

Wrapping callback functions is very tricky. I will take a look when I have a chance to see what the issue is, but it may take some time before I have it fixed.

**Comment by jf---** [comment]
Thanks @johnwason , I'm familiar with the limits of SWIG I've worked on [pythonocc](https://github.com/tpaviot/pythonocc-core/) extensively, which is also `SWIG` based. The issue is mostly namespaces related, the `set` function doesn't really invoke much.  `pybind11` has [an interesting approach to handling callbacks](https://indico.cern.ch/event/648602/contributions/2636804/attachments/1481481/2297505/Meeting_06.22.17.pdf). 

Any thoughts on how to move fwd regarding using the `descartes` planner?

**Comment by johnwason** [comment]
I use SWIG "directors" to handle the callbacks. There are some macros that generate a base class, and then the Python wrapper class extends the base class.

There is a SWIG file with the macro definitions that make it all work:

https://github.com/tesseract-robotics/tesseract_python/blob/master/tesseract_python/swig/tesseract_std_function.i

It looks like the customized typemap is not being applied for the field `target_pose_sampler`. It is likely that function parameters are using the correct typemap, but not the field assignment.

**Comment by johnwason** [comment]
@jf--- please send me a message on my website https://www.wasontech.com/contact-us

**Comment by jf---** [comment]
✅ thx for the invite!

**Comment by johnwason** [comment]
@jf--- can you try the wheels in 

https://github.com/tesseract-robotics/tesseract_python/suites/18704221744/artifacts/1088812345

This should have the sampling function fixed. You can install wheel files using pip by pointing to the file absolute location. Make sure you use the right file for your system and python version.

**Comment by johnwason** [comment]
I have tesseract running on Mac OSX arm64. See https://github.com/tesseract-robotics/tesseract/discussions/970

**Comment by johnwason** [comment]
Hi @jf--- have you had a chance to test these fixes? The macos packages should have the callback function working.

**Comment by jf---** [comment]
hi @johnwason yeah I noticed the use of `delocate` and tried an install, but seems a `env` var is missing:


```bash
========================================================= ERRORS =========================================================
__________________________ ERROR collecting tesseract_collision/test_collision_box_cone_unit.py __________________________
tesseract_collision/test_collision_box_cone_unit.py:9: in <module>
    TESSERACT_SUPPORT_DIR = os.environ["TESSERACT_SUPPORT_DIR"]
<frozen os>:685: in __getitem__
    ???
E   KeyError: 'TESSERACT_SUPPORT_DIR'
_________________________ ERROR collecting tesseract_collision/test_collision_mesh_mesh_unit.py __________________________
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/python.py:520: in importtestmodule
    mod = import_path(
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/pathlib.py:584: in import_path
    importlib.import_module(module_name)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
<frozen importlib._bootstrap>:1381: in _gcd_import
    ???
<frozen importlib._bootstrap>:1354: in _find_and_load
    ???
<frozen importlib._bootstrap>:1325: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:929: in _load_unlocked
    ???
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:169: in exec_module
    source_stat, co = _rewrite_test(fn, self.config)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/_pytest/assertion/rewrite.py:351: in _rewrite_test
    tree = ast.parse(source, filename=strfn)
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/ast.py:52: in parse
    return compile(source, filename, mode, flags,
E     File "/Users/jelle/Code/CADCAM/tesseract_python_orig/tesseract_python/tests/tesseract_collision/test_collision_mesh_mesh_unit.py", line 1
E       import numpy as np
E   IndentationError: unexpected indent
____________________________ ERROR collecting tesseract_motion_planning/test_ompl_planner.py _____________________________
ImportError while importing test module '/Users/jelle/Code/CADCAM/tesseract_python_orig/tesseract_python/tests/tesseract_motion_planning/test_ompl_planner.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tesseract_motion_planning/test_ompl_planner.py:18: in <module>
    from tesseract_robotics.tesseract_motion_planners_ompl import RRTConnectConfigurator, \
E   ImportError: cannot import name 'OMPLRealVectorPlanProfile' from 'tesseract_robotics.tesseract_motion_planners_ompl' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tesseract_robotics/tesseract_motion_planners_ompl/__init__.py)
________________________ ERROR collecting tesseract_task_composer/test_tesseract_task_composer.py ________________________
ImportError while importing test module '/Users/jelle/Code/CADCAM/tesseract_python_orig/tesseract_python/tests/tesseract_task_composer/test_tesseract_task_composer.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/importlib/__init__.py:90: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tesseract_task_composer/test_tesseract_task_composer.py:8: in <module>
    from tesseract_robotics.tesseract_environment import Environment, AnyPoly_wrap_EnvironmentConst
E   ImportError: cannot import name 'AnyPoly_wrap_EnvironmentConst' from 'tesseract_robotics.tesseract_environment' (/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tesseract_robotics/tesseract_environment/__init__.py)
```

**Comment by johnwason** [comment]
`TESSERACT_SUPPORT_DIR` env variable needs to be set to the local file directory location of `tesseract_support` from the tesseract repository.

**Comment by jf---** [comment]
this is a significant issue since there are quite a nr of env vars that setup tesseract. I've moved these to the root `__init__.py` such that handling env vars is more integrated.

**Comment by johnwason** [comment]
The env var is only used for tests.

https://github.com/tesseract-robotics/tesseract_python/blob/master/tesseract_python/tests/tesseract_support_resource_locator.py
